title: HRI Fall 2016 Symposium
description: Digital Scholarly Editions and Modern Greek Studies workshop - Athens, April 2017
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
