title: Ψηφιακές Εκδόσεις και Νεοελληνικές Σπουδές
subtitle: 24-28 Απριλίου 2017, <a href="http://transition.nlg.gr">Εθνική Βιβλιοθήκη της Ελλάδος (ΚΠΣΙΝ) </a>, Αθήνα
description: Digital Scholarly Editions and Modern Greek Studies | <a href= "http://dixit.uni-koeln.de">DiXiT</a> workshop 
google_analytics: 
url: https://dixit-eu.github.io/Digital-Scholarly-EditionsGR-workshop/
twitter_username: dixit-eu
github_username: dixit-eu
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
